# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarspwa', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='auth',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='endpoint',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='p256dh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
